/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CarConfiguration = IDL.Record({
  'bodyColor' : IDL.Text,
  'model' : IDL.Text,
  'accessories' : IDL.Vec(IDL.Text),
  'wheelStyle' : IDL.Text,
  'interiorColor' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyConfiguration' : IDL.Func([], [IDL.Opt(CarConfiguration)], ['query']),
  'getUserConfiguration' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CarConfiguration)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllConfigurations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, CarConfiguration))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveConfiguration' : IDL.Func([CarConfiguration], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CarConfiguration = IDL.Record({
    'bodyColor' : IDL.Text,
    'model' : IDL.Text,
    'accessories' : IDL.Vec(IDL.Text),
    'wheelStyle' : IDL.Text,
    'interiorColor' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyConfiguration' : IDL.Func([], [IDL.Opt(CarConfiguration)], ['query']),
    'getUserConfiguration' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CarConfiguration)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllConfigurations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, CarConfiguration))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveConfiguration' : IDL.Func([CarConfiguration], [], []),
  });
};

export const init = ({ IDL }) => { return []; };